package com.teamlms.backend.domain.alarm.enums;

public enum AlarmType {
    MENTORING_APPLICATION_STATUS,
    MENTORING_QUESTION_ANSWERED,
    MENTORING_NEW_APPLICATION,
    MENTORING_CHAT_MESSAGE,
    COMMUNITY_COMMENT,
    QNA_COMMENT,
    QNA_NEW_QUESTION,
    CURRICULAR_SCORE_ASSIGNED,
    CURRICULAR_GRADE_CONFIRMED,
    EXTRA_SESSION_CREATED,
    EXTRA_SESSION_VIDEO_UPLOADED,
    EXTRA_OFFERING_COMPLETED,
    NOTICE_NEW,
    SURVEY_NEW,
    STUDY_RENTAL_REQUESTED,
    STUDY_RENTAL_APPROVED,
    STUDY_RENTAL_REJECTED
}
