package com.teamlms.backend.domain.alarm.enums;

public enum AlarmType {
    MENTORING_APPLICATION_STATUS,
    MENTORING_QUESTION_ANSWERED,
    MENTORING_NEW_APPLICATION,
    MENTORING_CHAT_MESSAGE,
    COMMUNITY_COMMENT,
    QNA_COMMENT,
    NOTICE_NEW,
    SURVEY_NEW,
    STUDY_RENTAL_APPROVED,
    STUDY_RENTAL_REJECTED
}
